#cloud-config

# /var/lib/rancher/conf/cloud-config.d/nfs.yml

# https://github.com/rancher/os/issues/641
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root 
    content: |
      #!/bin/bash
      [ ! -e /usr/bin/docker ] && ln -s /usr/bin/docker.dist /usr/bin/docker
      mkdir -p /mnt/nfs-1                                                      
      mkdir -p /mnt/nfs-2                                                      
      cloud-init-execute

rancher:
  services:
    nfs:
      image: d3fk/nfs-client
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      net: host
      privileged: true
      restart: always
      volumes:
      - /usr/bin/iptables:/sbin/iptables:ro
        
mounts:                                                                        
- ["nfs_server_ip:/", "/mnt/nfs-1", "nfs4", ""]                                 
- ["nfs_server_ip:/", "/mnt/nfs-2", "nfs4", ""]
